### ISSUE TITLE
Flipped digits due to wrong transpose

### ISSUE THREAD

**Issue by ghost** [RoshanRane/segmentation-moving-MNIST#1]
The digits are horizontally flipped due to this line which also inverts width and height

https://github.com/RoshanRane/segmentation-moving-MNIST/blob/a2634eef648a883c738f58607b39413a8241c5b6/moving_mnist_for_segmentation/dataset.py#L69

Which I believe should be:
`img_std = img_std.clip(0, 255).transpose(1,2,0).squeeze()`

**Comment by RoshanRane** [comment]
Thank you for reporting. Fixed in latest commit
